### ISSUE TITLE
Possible typo in gnokey query command in tutorial.md

### ISSUE THREAD

**Issue by kristovatlas** [leohhhn/gnoland_zero_to_hero#2]
> $ gnokey query bank/balances/bank/balances/g10rdr9mhc7xzlyqt9fu3nhl95jy8hmfdyws8yds

I think `bank/balances/` perhaps should be listed only once.

**Comment by leohhhn** [comment]
Hey, you're right. Thanks for the heads up. I have migrated the tutorial to [this](https://github.com/leohhhn/gno/blob/from_zero_to_gnoland_hero/examples/gno.land/whitelist/tutorial.md) repo, and fixed the typo.
